# Schema for the configuration files of the Config Entity Example module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/config_entity_example.robot.marvin.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

nt8booking_enquiry.settings:
  type: mapping
  label: 'NT8 Booking Enquiry'
  mapping:
    error_codes:
      type: string
      label: 'Error Codes'
